runtime: python39

instance_class: F4

app_engine_apis: true

inbound_services:
  - warmup

automatic_scaling:
  min_idle_instances: 1

handlers:
  - url: /
    static_files: static/index.html
    upload: static/index.html
    secure: always

  - url: /static
    static_dir: static
    secure: always

  - url: /.*
    script: auto
    secure: always
