runtime: python39

instance_class: F4

app_engine_apis: true


handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /static
  static_dir: static

- url: /.*
  script: auto